### ISSUE TITLE
Unable to run "box testbox run" on CFML CI Tools

### ISSUE THREAD

**Issue by michaelborn** [foundeo/cfml-ci-tools#6]
Attempting to run `testbox run` with Lucee throws an error, as Lucee evidently cannot find the `encodeForURL() method:

Command:

```
docker run \
    --rm \
    --entrypoint "box" \
    -v $PWD:/app \
    ghcr.io/foundeo/cfml-ci-tools/cfml-ci-tools:1.0.5 \
    "testbox run runner=http://localhost:9999/tests/index.cfm"
```

This throws:

```
ERROR (5.4.2+00453)

In the OSGi Bundle with the name [esapi.extension] and the version [2.2.3.1-0-SNAPHOT] was no class with name [org.lucee.extension.esapi.functions.EncodeForURL] found. org.lucee.extension.esapi.functions.EncodeForURL
  caused by: lucee.commons.lang.ClassException
  In the OSGi Bundle with the name [esapi.extension] and the version [2.2.3.1-0-SNAPHOT] was no class with name [org.lucee.extension.esapi.functions.EncodeForURL] found. org.lucee.extension.esapi.functions.EncodeForURL


/root/.CommandBox/cfml/system/modules_app/testbox-commands/commands/testbox/run.cfc: line 251
249: 			else if ( boxOptions.keyExists( thisOption ) && len( boxOptions[ thisOption ] ) ) {
250: 				if ( isSimpleValue( boxOptions[ thisOption ] ) ) {
251: 					arguments.testboxURL &= "&#encodeForURL( thisOption )#=#encodeForURL( boxOptions[ thisOption ] )#";
252: 				} else {
253: 					print.yellowLine(
called from /root/.CommandBox/cfml/system/modules_app/testbox-commands/commands/testbox/run.cfc: line 123
called from /root/.CommandBox/cfml/system/services/CommandService.cfc: line 345
called from /root/.CommandBox/cfml/system/services/CommandService.cfc: line 158
called from /root/.CommandBox/cfml/system/Shell.cfc: line 784
called from /root/.CommandBox/cfml/system/Bootstrap.cfm: line 119

lucee.runtime.exp.NativeException: In the OSGi Bundle with the name [esapi.extension] and the version [2.2.3.1-0-SNAPHOT] was no class with name [org.lucee.extension.esapi.functions.EncodeForURL] found. org.lucee.extension.esapi.functions.EncodeForURL
	at lucee.commons.lang.ClassUtil.loadClassByBundle(Unknown Source)
	at lucee.commons.lang.ClassUtil.loadClassByBundle(Unknown Source)
	at lucee.runtime.functions.FunctionHandlerPool.use(Unknown Source)
	at lucee.runtime.functions.FunctionHandlerPool.invoke(Unknown Source)
	at system.modules_app.testbox_commands360.commands.testbox.run_cfc$cf.udfCall(/commandbox/system/modules_app/testbox-commands/commands/testbox/run.cfc:251)
	at lucee.runtime.type.UDFImpl.implementation(Unknown Source)
	at lucee.runtime.type.UDFImpl._call(Unknown Source)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source)
	at system.modules_app.testbox_commands360.commands.testbox.run_cfc$cf.udfCall(/commandbox/system/modules_app/testbox-commands/commands/testbox/run.cfc:123)
	at lucee.runtime.type.UDFImpl.implementation(Unknown Source)
	at lucee.runtime.type.UDFImpl._call(Unknown Source)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.ComponentImpl._call(Unknown Source)
	at lucee.runtime.ComponentImpl._call(Unknown Source)
	at lucee.runtime.ComponentImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source)
	at system.services.commandservice_cfc$cf.udfCall1(/commandbox/system/services/CommandService.cfc:345)
	at system.services.commandservice_cfc$cf.udfCall(/commandbox/system/services/CommandService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(Unknown Source)
	at lucee.runtime.type.UDFImpl._call(Unknown Source)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source)
	at system.services.commandservice_cfc$cf.udfCall1(/commandbox/system/services/CommandService.cfc:158)
	at system.services.commandservice_cfc$cf.udfCall(/commandbox/system/services/CommandService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(Unknown Source)
	at lucee.runtime.type.UDFImpl._call(Unknown Source)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.ComponentImpl._call(Unknown Source)
	at lucee.runtime.ComponentImpl._call(Unknown Source)
	at lucee.runtime.ComponentImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source)
	at system.shell_cfc$cf.udfCall4(/commandbox/system/Shell.cfc:784)
	at system.shell_cfc$cf.udfCall(/commandbox/system/Shell.cfc)
	at lucee.runtime.type.UDFImpl.implementation(Unknown Source)
	at lucee.runtime.type.UDFImpl._call(Unknown Source)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.ComponentImpl._call(Unknown Source)
	at lucee.runtime.ComponentImpl._call(Unknown Source)
	at lucee.runtime.ComponentImpl.callWithNamedValues(Unknown Source)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(Unknown Source)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(Unknown Source)
	at _commandbox46.cfml.system.bootstrap_cfm$cf.call(/__commandbox_root/.CommandBox/cfml/system/Bootstrap.cfm:119)
	at lucee.runtime.PageContextImpl._doInclude(Unknown Source)
	at lucee.runtime.PageContextImpl._doInclude(Unknown Source)
	at lucee.runtime.PageContextImpl.doInclude(Unknown Source)
	at 1hakaskpj4qmq.call(Unknown Source)
	at lucee.runtime.compiler.Renderer.tag(Unknown Source)
	at lucee.runtime.compiler.Renderer.script(Unknown Source)
	at lucee.runtime.jsr223.ScriptEngineImpl.eval(Unknown Source)
	at lucee.runtime.jsr223.ScriptEngineImpl.eval(Unknown Source)
	at cliloader.LoaderCLIMain.execute(LoaderCLIMain.java:330)
	at cliloader.LoaderCLIMain.execute(LoaderCLIMain.java:155)
	at cliloader.LoaderCLIMain.main(LoaderCLIMain.java:582)
Caused by: lucee.commons.lang.ClassException: In the OSGi Bundle with the name [esapi.extension] and the version [2.2.3.1-0-SNAPHOT] was no class with name [org.lucee.extension.esapi.functions.EncodeForURL] found. org.lucee.extension.esapi.functions.EncodeForURL
	... 60 more
```

Is this a Lucee versioning issue? Or a Lucee extension version issue? Perhaps the ESAPI extension is not installed? (Though the error message implies the esapi OSGI bundle is definitely available...)

I can't tell if this is an issue with `cfml-ci-tools` or somewhere "upstream". :man_shrugging:

**Comment by michaelborn** [comment]
Ok, so I get the exact same results on `v1.0.4`.

`v1.0.3`, however, throws `No matching function [ENCODEFORURL] found`. No mention of the ESAPI extension. So I _suspect_ this is an issue with Lucee auto-installing the wrong version of the ESAPI extension.

**Comment by pfreitag** [comment]
yeah, for some reason they do not include the ESAPI extension in the lucee light version, so installing that should fix this problem

**Comment by pfreitag** [comment]
@michaelborn what version are you using? looks like we have already been down this road before:

https://github.com/foundeo/cfml-ci-tools/commit/55ba71d2bcc267721c4d2d09c0bcf1478f78167a#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

**Comment by pfreitag** [comment]
Ah, I see you posted the versions...

**Comment by pfreitag** [comment]
Ok, so strange error message, is that version of the ESAPI extension broken? It looks like it has the extension, but unable to find the function. I'll have to look at that when I have more time.

Also, I talked to Zac about bundling esapi in lucee light, hopefully a future version of lucee light will bundle it by default: https://luceeserver.atlassian.net/browse/LDEV-3857

**Comment by michaelborn** [comment]
Yeah, we've definitely "been down this road before", but the Lucee extension install should have fixed this. That's why I was confused - because the ESAPI extension is definitely installed in this case... so it's a different error after all.

**Comment by michaelborn** [comment]
I think you're right.... the lucee extension may be broken right now. It looks like Zac was working on bundling this into Lucee Light:

![Screenshot from 2022-01-31 13-07-21](https://user-images.githubusercontent.com/8106227/151848772-ef15aefb-0479-4a56-9f1f-3990c52e1af0.png)

**Comment by pfreitag** [comment]
I am trying to use an exact version of ESAPI, one that I know has worked on Lucee light previously. Version 1.0.6 is being pushed right now, once it is done building it should be ready to try, let me know if it works for you.

**Comment by michaelborn** [comment]
You win the internet, @pfreitag ! That did the trick!

Now time for me to let LAS know they've got a broken extension on their hands...

**Comment by pfreitag** [comment]
always nice to win the internet, thanks! 

Post ticket here if you end up filing one or finding one... It might just be that the latest version of the ESAPI extension is only going to work on the latest Lucee (which switched to log4j2). .

**Comment by pfreitag** [comment]
Looks like I forgot to close this ticket
